name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pylint

      - name: Run tests and generate coverage report
        run: |
          pytest --junitxml=test/reports/xunit.xml --cov=src --cov-report=xml:test/reports/coverage.xml --cov-report=html:test/reports/html

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: test/reports/coverage.xml

      - name: Upload Coverage Report to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.coverageReportPaths=test/reports/coverage.xml
