name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint bandit pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run linters
        run: |
          flake8 src/ test/ main.py
          pylint src/ test/ main.py
          bandit -r src/

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=src --cov-report=xml
          mv coverage.xml coverage-reports/coverage.xml

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@v2.1.0
        with:
          args: >
            -Dsonar.organization=deviscoutb
            -Dsonar.projectKey=ISCODEVUTB_DSTeam_BLAHX3
            -Dsonar.sources=src/
            -Dsonar.tests=test/
            -Dsonar.python.coverage.reportPaths=coverage-reports/coverage.xml
            -Dsonar.test.exclusions=**/test/**
            -Dsonar.verbose=true
