name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Ejecutar en cada push a la rama main
  pull_request:
    branches:
      - main  # Ejecutar en PRs hacia main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pylint

      - name: Ejecutar pruebas y generar reportes
        run: |
          pytest --junitxml=tests/reports/xunit.xml --cov=src --cov-report=xml:tests/reports/coverage.xml

      - name: Analizar con SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=ISCODEVUTB_DSTeam_BLAHX3 \
            -Dsonar.organization=deviscoutb \
            -Dsonar.sources=src \
            -Dsonar.tests=tests \
            -Dsonar.python.version=3.10 \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.exclusions=**/migrations/**,**/*.pyc,**/__pycache__/**,venv/**,docs/** \
            -Dsonar.python.pylint=$(which pylint) \
            -Dsonar.python.pylint_config=.pylintrc \
            -Dsonar.python.xunit.reportPath=tests/reports/xunit.xml \
            -Dsonar.coverageReportPaths=tests/reports/coverage.xml
