name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Asegurar que pytest y pytest-cov están instalados

      # Ejecutar pruebas y generar reporte de cobertura
      - name: Run tests with coverage
        env:
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          PYTHONPATH=$PWD pytest --cov=mi_paquete --cov-report=term --cov-report=html --cov-report=xml

      # Depuración en caso de error
      - name: Debug PYTHONPATH (in case of errors)
        if: failure()
        run: python -c "import sys; print(sys.path)"

      # Guardar el reporte de cobertura como un artifact para descargarlo después
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov  # Carpeta donde pytest guarda el reporte en HTML

